repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        files: \.py$
        args: ["--profile", "google"]

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        name: Format Python code with YAPF
        files: \.py$
        additional_dependencies: ["toml"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Format Markdown files
        files: \.md$
        language_version: "20.11.1"
      - id: prettier
        name: Format YAML files
        files: \.(yaml|yml)$
        language_version: "20.11.1"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Fix end-of-file newline
