[project]
name = "qryptify-ingestor"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "httpx>=0.27",
  "websockets>=12.0",
  "pyyaml>=6.0",
  "psycopg[binary]>=3.2",
  "tenacity>=9.0",
  "pytz>=2024.1",
]
