pairs:
  - BTCUSDT/1h
  - ETHUSDT/1h
  - BNBUSDT/1h
  - BTCUSDT/1m
rest:
  klines_limit: 1500
  endpoint: "https://fapi.binance.com"
ws:
  endpoint: "wss://fstream.binance.com/stream"
  reconnect_initial_ms: 500
  reconnect_max_ms: 8000
db:
  dsn: "postgresql://postgres:postgres@localhost:5432/qryptify"
safety:
  max_clock_skew_ms: 1000
backfill:
  start_date: "2023-01-01T00:00:00Z" # min boundary
