pairs:
  - BTCUSDT/4h
  - ETHUSDT/4h
  - BNBUSDT/4h
rest:
  klines_limit: 1500
  endpoint: "https://fapi.binance.com"
ws:
  endpoint: "wss://fstream.binance.com/stream"
db:
  dsn: "postgresql://postgres:postgres@localhost:5432/qryptify"
backfill:
  start_date: "2023-01-01T00:00:00Z" # min boundary
