name: Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  pytest:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff mypy
      - name: Run ruff (lint)
        run: ruff check .
      - name: Run mypy (type check)
        run: |
          mypy qryptify qryptify_ingestor qryptify_strategy
      - name: Run tests
        run: pytest -q
